name: Basic CI: formatting, linting, testing
on: [push]
jobs:
  basic-ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” ${{ github.repository }} @ ${{ github.ref }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: make install
      - run: make format
      - run: make lint
      - run: make test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
